jwt:
  header: Authorization
  secret: swjtuhcxxgcx
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      login: "auth/login"
      refresh: "auth/refresh"
      register: "auth/register"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/career_guidance?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    generator:
      write-numbers-as-strings: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: edu.swjtuhc.cgService.mapper

